diary/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include

urlpatterns = [path("admin/", admin.site.urls), path("", include("diaryapp.urls"))]

if settings.DEBUG:
	urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diaryapp/urls.py
from django.contrib.auth.views import logout_then_login
from django.urls import path

from .views import (
    CustomLogoutView, CustomLoginView, UserCreateView, index,
)

app_name = "diaryapp"


urlpatterns = [
    path("", view=index, name="index"),
    path("register/", view=UserCreateView.as_view(), name="register"),
    path("login/", view=CustomLoginView.as_view(), name="login"),
    path("logout/", view=CustomLogoutView.as_view(), name="logout")
]

diaryapp/models.py
from logging import getLogger
from typing import Dict
from urllib.error import URLError
from urllib.request import urlopen

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.timezone import now

logger = getLogger("stdout")



def calc_max_length(data: Dict):
    return len(max(data, key=lambda x: len(x)))


def reaper(pk: int):
    try:
        target = Target.objects.get(pk=pk)
        target.status = "failed"
        target.save()
    except Target.DoesNotExists:
        logger.error(f"With trying set `failed` flag for Target with pk {pk}, Target was not found")


def future_date(value):
    if value <= now():
        raise ValidationError("planned_datetime can`t be in the past")

class Note(models.Model):
    created_at = models.DateTimeField()
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="notes")
    
    note = models.TextField(null=True, blank=True)


class Target(models.Model):
    statuses = {
        "process": "В процессе",
        "done": "Выполнено",
        "failed": "Провалено",
        "canceled": "Отменено"
    }
    types = {
        "ultimate": "UT",
        "story": "Сюжет",
        "additional": "Дополнение",
        "task": "Задача"
    }
    
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="creator")
    created_at = models.DateTimeField(auto_now_add=True)
    type = models.CharField(max_length=calc_max_length(types), default="task", choices=types)
    
    over_at = models.DateTimeField(null=True)
    planned_datetime = models.DateTimeField(null=True, validators=(future_date,))
    status = models.CharField(max_length=calc_max_length(statuses), default="process", choices=statuses)
    group_priority = models.IntegerField(default=0, help_text="priority grouped by type")
    condition = models.TextField(max_length=255, help_text="user condition for determining the task status")
    description = models.TextField(max_length=1000, help_text="free textarea with any description")
    
    file = models.FileField(upload_to="tasks/attachments")


def is_resource_available(value):
    try:
        urlopen(value)
    except URLError:
        raise ValidationError(f"resource with url {value} not available")
    

class Resource(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="resources")
    
    domain = models.CharField(max_length=100, validators=(is_resource_available,))
    status = models.BooleanField(default=True)

class Book(models.Model):
    types = {
        "unknown": "Неизвестно",
        "0": "0",
        "some": "Некоторое",
        "volume": "Объёмное",
        "full": "Полное",
    }
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="books")
    
    author = models.CharField(max_length=30)
    name = models.CharField(max_length=15)
    file = models.FileField(upload_to="books", null=True)
    comprehension = models.CharField(max_length=calc_max_length(types), default="unknown", choices=types)
    
    class Meta:
        unique_together = ("author", "name")



class Area(models.Model):
    types = {
        "programming_language": "Язык программирования",
        "technology": "Технология",  # Инструмент управления технологией
        "science": "Наука",  # Область
        "paradigm": "Парадигма",
        "method": "Метод",
        "Framework": "Фреймворк",
        "library": "Библиотека",
        "language": "Язык",
        "other": "Другое",
    }
    grades = {
        "0": "0",
        "beginner": "Базовый",
        "middle": "Средний",
        "advanced": "Продвинутый"
    }
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="areas")

    name = models.CharField(max_length=20)
    type = models.CharField(max_length=calc_max_length(types), default="other", choices=types)
    grade = models.CharField(max_length=calc_max_length(grades), default="0", choices=grades)
    experience = models.TextField(max_length=1000, null=True, blank=True)
    
    
def params_factory():
    return {
        "push-ups": 0,
        "squats": 0,
        "bar": 0, #s
        "pull-ups": 0,
        "run": 0, #m
    }

class Profile(models.Model):
    owner = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    
    params = models.JSONField(default=params_factory)

diaryapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CustomUserCreationForm(UserCreationForm):
	usable_password = None
	class Meta:
		model = User
		fields = "username", "password1", "password2"

diaryapp/views.py
from logging import getLogger

from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_not_required
from django.contrib.auth.views import LoginView, LogoutView, logout_then_login
from django.http import HttpRequest
from django.shortcuts import render
from django.utils.decorators import classonlymethod
from django.views.generic import CreateView
from rest_framework.reverse import reverse_lazy

from diaryapp.forms import CustomUserCreationForm

logger = getLogger("stdout")


class UserCreateView(CreateView):
    form_class = CustomUserCreationForm
    template_name = "diaryapp/register.html"
    success_url = reverse_lazy("diaryapp:index")
    
    @classonlymethod
    def as_view(cls, **initkwargs):
        return login_not_required(super().as_view(**initkwargs))
    
    def form_valid(self, form):
        response = super().form_valid(form)
        login(self.request, self.object)
        return response

class CustomLoginView(LoginView):
    template_name = "diaryapp/login.html"
    redirect_authenticated_user = True
    success_url_allowed_hosts = "127.0.0.1", "localhost"

class CustomLogoutView(LogoutView):
    template_name = "diaryapp/logout.html"


# if self.status in ("failed", "done"):
#     self.over_at = now()
#
# settings.scheduler.add_job(reaper, "date", id=f"Target_{self.pk}", run_date=self.planned_datetime, args=[self.pk],
#                            replace_existing=True)

# @login_not_required
# def login_view(request: HttpRequest):
#     if request.method == "POST":
#         username = request.POST.get("username")
#         password = request.POST.get("password")
#         user = authenticate(request, username=username, password=password)
#         if user is not None:
#             login(request, user)
#             next_ = request.POST.get("next")
#             if next_ is not None:
#                 redirect(next_)
#             else:
#                 redirect(reverse("diaryapp:index"))
#         else:
#             return render(request, "diaryapp:login.html", context={
#                 "error": "Wrong username or password",
#                 "username": username,
#                 "password": password,
#             })
#     elif request.method == "GET":
#         if not request.user.is_authenticated:
#             return render(request, "diaryapp:login.html")
#         else:
#             redirect(reverse("diaryapp:index"))

@login_not_required
def index(request: HttpRequest):
    return render(request, "diaryapp/index.html")

def diary(request: HttpRequest):
    ...
    

diaryapp/templates/diaryapp/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="author" content="Wynardtage">
	<meta name="description" content="EFP-Diary for every day">
	<meta name="keywords" content="EFP-Diary">
	<meta name="viewport" content="width=device-width; initial-scale=1.0">
	<meta http-equiv="content-type" content="text/html">
	<title>
        {% block title %}
            Diary
        {% endblock %}
    </title>
<!--	{% load static %}-->
<!--    <link rel="stylesheet" href="{% static 'css/styles.css' %}">-->
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
</head>
<body>
    {% block body %}
        Diary
    {% endblock %}
</body>
</html>

diaryapp/templates/diaryapp/index.html
{% extends "diaryapp/base.html" %}

{% block body %}
	<header>
		<h1>Diary</h1>
		<div>
			<p><a href="{% url 'diaryapp:register' %}">Регистрация</a></p>
			{% if user.is_authenticated %}
				<form method="post" action="{% url 'diaryapp:logout' %}">
					{% csrf_token %}
					<button type="submit">Выход</button>
				</form>
			{% else %}
				<p><a href="{% url 'diaryapp:login' %}">Вход</a></p>
			{% endif %}
		</div>
	</header>
	<section>
		<div>
			Diary
		</div>
	</section>
{% endblock %}

diaryapp/templates/diaryapp/login.html
{% extends "diaryapp/base.html" %}

{% block title %}
	Вход
{% endblock %}

{% block body %}
	<form method="post" action="{% url 'diaryapp:login' %}">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Войти</button>
	</form>
	<a href="{% url 'diaryapp:index' %}">На главную</a>
{% endblock %}

diaryapp/templates/diaryapp/register.html
{% extends "diaryapp/base.html" %}

{% block title %}
	Регистрация
{% endblock %}

{% block body %}
	<form method="post" action="{% url 'diaryapp:register' %}">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Зарегистрироваться</button>
	</form>
	<a href="{% url 'diaryapp:index' %}">На главную</a>
{% endblock %}